# permissions for end users to edit cloudbuckets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cloudbucket-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cloud-storage-controller
    app.kubernetes.io/part-of: cloud-storage-controller
    app.kubernetes.io/managed-by: kustomize
  name: cloudbucket-editor-role
rules:
- apiGroups:
  - mygroup.example.com
  resources:
  - cloudbuckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mygroup.example.com
  resources:
  - cloudbuckets/status
  verbs:
  - get
