apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cloud-storage-controller
    app.kubernetes.io/part-of: cloud-storage-controller
    app.kubernetes.io/managed-by: kustomize
  annotations:
      iam.gke.io/gcp-service-account: cloud-storage-controller@rich-mountain-428806-r0.iam.gserviceaccount.com
  name: controller-manager
  namespace: system