apiVersion: mygroup.example.com/v1
kind: CloudBucket
metadata:
  labels:
    app.kubernetes.io/name: cloudbucket
    app.kubernetes.io/instance: cloudbucket-sample
    app.kubernetes.io/part-of: cloud-storage-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cloud-storage-controller
  annotations:
    test: testw
  name: my-bucket-11
  namespace: default
spec:
  projectID: rich-mountain-428806-r0
  bucketName: my-unique-bucket-784509348-0021
  deletePolicy: Delete
  location: eu
---
apiVersion: mygroup.example.com/v1
kind: CloudBucket
metadata:
  labels:
    app.kubernetes.io/name: cloudbucket
    app.kubernetes.io/instance: cloudbucket-sample
    app.kubernetes.io/part-of: cloud-storage-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cloud-storage-controller
  annotations:
    test: testw
  name: my-bucket-21
  namespace: default
spec:
  projectID: rich-mountain-428806-r0
  bucketName: my-unique-bucket-6735765856-0011
  deletePolicy: Orphan
  location: asia